# This is a basic workflow to help you get started with Actions

name: Build and deploy Jekyll site to GitHub Pages

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - new-articles
  create:
    branches:
      - new-articles

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  github-pages:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: helaili/jekyll-action@2.0.1
      env:
        JEKYLL_PAT: ${{ secrets.JEKYLL_PAT }}

  update-master:
    needs: github-pages
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: gh-pages
    - name: Merge gh-pages -> master
      uses: devmasx/merge-branch@v1.3.0
      with:
        type: now
        head_to_merge: gh-pages 
        target_branch: master
        github_token: ${{ secrets.PUSH_TOKEN }}
